image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:

  - java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -jar aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info  