version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app

  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass